id: 8a03fb0bbad64b96a8a177785869f7be
initial_creation_type: ocr
source_metadata:
  volumes:
    e81b78ad1c704331b6783aebf579043e:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
